### ISSUE TITLE
My findings, Issues and Suggestion

### ISSUE THREAD

**Issue by SjamonDaal** [hql287/Manta#95]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [X] It's a bug.
- [X] I'm requesting a new feature.

**Which version are you using?**

- [X] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

I'm using macOS High Sierra

**Describe your issue**

- The font styling doen't work (image 1)
- When creating a new customer while creating a new invoice, after saving the email entered shows in the phone number box. (image 2)
- Field of view falls out of my screen (Macbook Air) (image 1)

Image 1
![schermafbeelding 2017-12-14 om 23 05 43](https://user-images.githubusercontent.com/4325936/34016749-534edd92-e123-11e7-8533-4e6b222ec223.png)

Image 2
![schermafbeelding 2017-12-14 om 23 12 04](https://user-images.githubusercontent.com/4325936/34017030-4d7b6c5e-e124-11e7-9e31-5d14d3a56bec.png)

**My Requests**
Please add support for the following items on my request,
- [ ] Translations or a simple lang file I can translate myself
- [x] Better Tax Management (Why is my tax added instead of calculated)
- [ ] Function to send the invoice to your customer (availability to setup your own mail server settings)
- [ ] Textbox to add bank account information to the invoice
- [x] Textbox to add your tax registration number to the invoice
- [x] Textbox to add your company registration number to the invoice
- [x] Due date for the inoice
- [x] Mark invoice as Paid
- [x] Mark invoice as Canceled
- [x] Mark invoice as Refunded (With a specific value + reason)
- [ ] Edit button to change clients
- [x] Option to set a default TAX value
- [ ] Option to set a default Note (With or without parameters like due date, value and bank account)
- [ ] Option to set default due date term (Always 14 days except if I specify different)
- [ ] Footer line (for your terms and or the locations of your terms)

If you need any help, hook me up ;)
I've made this Request list in 10 minutes so if you need any more items feel free to ask.

**Comment by SjamonDaal** [comment]
Afterwards,

I found some updates on the git about some of my suggestions. Please ignore everything that's already done. My suggestions and bugs are based on the dmg download v1.0.0

If there is a newer version available, please hook me up!

**Comment by hql287** [comment]
@SjamonDaal Thanks for taking the time for making these suggestions. All of your issues are resolved and will be included in the next release. 

I'm already working on some of your requests. Refers to this issue https://github.com/hql287/Manta/issues/90 for more info on the tax feature

I like your suggestions on Due Date, will add it to the list.

**Comment by hql287** [comment]
@SjamonDaal It's been 3 weeks and some of your requests have been made. 
Right now there's only a few left:

- [ ] Support for multiple languages. See #9 
- [ ] Edit invoice. See #57 
- [ ] Note Templates. See #119 
- [ ] Send email via email. No issue created yet.
- [ ] Better DueDate. Not issue created yet.

I'm closing this but feel free to create new issues for each feature request that's not already on the list.
